name: Raychi
favicon: null
layout_spectrum: 0.07075
typography_spectrum: 0.60963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e1db9d'
    - '#72705f'
    - '#a9a356'
    - '#010101'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.08489447878673673
  rhythmicContrast: 0.75
purpose: []
